DEBUG 2024-05-20 17:04:14.583 UTC: 	 CRAB Client version: v3.240416
DEBUG 2024-05-20 17:04:14.584 UTC: 	 Running on: Linux lxplus714.cern.ch 3.10.0-1160.118.1.el7.x86_64 #1 SMP Wed Apr 24 16:01:50 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-05-20 17:04:14.584 UTC: 	 Executing command: 'submit'
DEBUG 2024-05-20 17:04:14.584 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/mkaramsi/.crab3
ERROR 2024-05-20 17:04:14.585 UTC: 	 CRAB configuration file crab_cfg.py not found.
ERROR 2024-05-20 17:04:14.585 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/lib/CRABClient/Commands/SubCommand.py", line 325, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/lib/CRABClient/Commands/SubCommand.py", line 53, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_cfg.py not found.
INFO 2024-05-20 17:04:14.608 UTC: 	 Log file is /afs/cern.ch/user/m/mkaramsi/public/hepmc/CMSSW_11_2_4/src/Rivet/crab.log
